apiVersion: v1
kind: Pod
metadata:
  name: dev
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  # nodeSelector:
    # kubernetes.io/hostname: 'grace.sciclone.wm.edu'
  containers:
    - name: dev-pod
      image: ghcr.io/stmorse/gg:latest
      # image: pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime
      resources:
        requests:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '4'
        limits:
          memory: '64Gi'
          nvidia.com/gpu: '1'
          cpu: '4'
      command: ['/bin/sh']
      args:
        - '-c'
        - |
          echo "Running container..."   # pod is for dev'ing scripts, run indef
          sleep infinity
      env:
        - name: HF_HOME
          value: '/sciclone/home/stmorse/.cache/huggingface/hub'
      volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
        - name: data
          mountPath: /sciclone/data10/twford/reddit/reddit
        - name: results
          mountPath: /sciclone/geograd/stmorse
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse
    - name: data
      nfs:
        server: 128.239.56.30
        path: /sciclone/data10/twford/reddit/reddit
    - name: results
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd/stmorse